#!/usr/bin/env bash
# script that installs nginx and posts hello world at its root

ssh ubuntu@3.84.158.82
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
uf allow 'Nginx HTTP'
service nginx start

curl -X POST ubuntu@3.84.158.82/var/www/html/index.nginx-debian.html -d '<html><body><h1>Hello, World!</h1></body></html>'

service nginx restart
