#!/usr/bin/env bash
# configures the server to redirect the '/redirect_me' page to
# another page
apt-get update
apt-get -y install nginx

NGINX_CONF="/etc/nginx/sites-available/default"
NEW_TEXT="server_name _;\n\trewrite ^\/redirect_me https:\/\/themainsamuel.tech permanent;"

cp $NGINX_CONF ${NGINX_CONF}.bak

if grep -q "server_name _;\n\trewrite" $NGINX_CONF;
then
        echo "Redirection already exists in the config file"
else
        sed -i "s/server_name _;/$NEW_TEXT/" $NGINX_CONF
fi

if sudo nginx -t;
then
        service nginx reload
        echo "Nginx configuration reloaded successfully."
else
        echo "Nginx configuration test failed. Please check the configuration."
        cp ${NGINX_CONF}.bak $NGINX_CONF
        service nginx reload
fi
