#!/usr/bin/env bash
# configures the server to redirect the '/redirect_me' page to
# another page
NGINX_CONF="/etc/nginx/sites-available/default"
REDIRECTION="location /redirect_me {
        return 301 http://themainsamuel.tech;
}"

sudo cp $NGINX_CONF ${NGINX_CONF}.bak

if grep -q "location /redirect_me" $NGINX_CONF;
then
        echo "Redirection already exists in the config file"
else
        sudo sed -i "/server {/a
        $REDIRECTION" $NGINX_CONF
fi
sudo nginx -t

if [ $? -eq 0 ]; then
        sudo service nginx reload
        echo "Nginx configuration reloaded successfully."
else
        echo "Nginx configuration test failed. Please check the configuration."
        sudo cp ${NGINX_CONF}.bak $NGINX_CONF
        sudo service nginx reload
fi
