#!/usr/bin/env bash
# custom 404 page '/404.html'
echo "Ceci n'est pas une page" | sudo tee /var/www/404.html

config_lines="root \/var\/www\/html;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
config_file_path="/etc/nginx/sites-available/default"

cp $config_file_path ${config_file_path}.bak

sed -i "s/root \/var\/www\/html;/$config_lines/" $config_file_path

if nginx -t;
then
	service nginx reload
	echo "Reload successful"
else
	echo "Unsuccessful configuration"
	cp ${config_file_path}.bak $config_file_path
	service nginx reload
fi
