#!/usr/bin/env bash
# makes nginx listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx reload
