#!/usr/bin/env bash
# This script displays a list of all currently running processes, 
# for all users, including those which might not have a TTY, in a user-oriented
# format and showing process hierarchy

ps -afux
