#!/usr/bin/env bash
# This script displays a list of all lines containing the bash word in the currently running processes, for all users, including those which might not have a TTY, in a user-oriented format and showing process hierarchy
# shellcheck disable=SC2009

ps -afux | grep "bash"
