#!/usr/bin/env bash
# This script kills the "4-to_infinity_and_beyond" script using "kill"

process_name="4-to_infinity_and_beyond"
pid=$(pgrep -f "$process_name")

if [ -n "$pid" ];
then
	kill "$pid"
fi
