#!/usr/bin/env bash
# This script kills the "4-to_infinity_and_beyond" script using "pkill"

process_name="4-to_infinity_and_beyond"
pid=$(pgrep -f "$process_name")

if [ -n "$pid" ];
then
	pkill -f "$process_name"
fi
