#!/usr/bin/env bash
# This script displays "Best School" 10 times but for the 4th and 8th iteration, displays "bad luck" and "good luck" respectively

i=1
while ((i <= 10)); do
       if [ $i = 4 ]
       then
	       echo "bad luck"
       elif [ $i = 8 ]
       then
	       echo "good luck"
       else
	       echo "Best School"
       fi
       ((i++))
done       
