#!/usr/bin/env bash
# This script displays numbers 1-20 but after the 4th, 9th and 17th iteration,
# displays "bad luck from China", "bad luck from Japan", and "bad luck from Italy" respectively

i=1
while ((i <= 20)); do
	echo "$i"
	case $i in 
		4)
	       		echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
       ((i++))
done       
