#!/usr/bin/env bash
# This script displays hours 0-12 with minutes 1-59 under each hour

hour=0
while ((hour <= 12)); do
	echo "Hour: $hour"
	min=1
	while ((min <= 59)); do
		echo "$min"
		((min++))
	done
	((hour++))
done       
