#!/usr/bin/env bash
# This script displays the content of the current directory in list format 
# where only the part of the name after the first dash is displayed

find ./ -type f | cut -d "/" -f 2 | cut -d "-" -f 2
